PackageIdentifier: Headlamp.Headlamp
PackageVersion: 0.24.0
Installers:
  - Architecture: x64
    InstallerLocale: en-US
    InstallerType: exe
    InstallerUrl: https://github.com/headlamp-k8s/headlamp/releases/download/v0.24.0/Headlamp-0.24.0-win-x64.exe
    InstallerSha256: 30ed4533d41ba1a86dc87f78dce7474839b217ad8ac311c0a19b0e4ed5b56793
    Scope: user
    InstallModes:
      - interactive
      - silent
    InstallerSwitches:
      Silent: /S
      SilentWithProgress: /S
    AppsAndFeaturesEntries:
      - DisplayName: Headlamp
        DisplayVersion: 0.24.0
        Publisher: Headlamp
        InstallerType: exe
    ReleaseDate: 2024-05-29
ManifestType: installer
ManifestVersion: 1.5.0
